# 21: #Uma lista em python serve para armazenar itens, e pode ser modificada. Ela é representada por colchetes [] e os itens são separados por vírgula.
# 22: #Um dicionario em python é uma coleção de pares chave-valor, onde cada chave é única e está associada a um valor. Ele é representado por chaves {} e os pares chave-valor são separados por vírgula. Os dicionários são mutáveis, o que significa que você pode adicionar, remover ou modificar os itens após a criação do dicionário.
# 23: Diferença entre append e insert: o append adiciona um intem no final da lista enquanto o insert adiciona em uma posição especifica da lista 
# 24: O método pop serve para remover um item de uma lista, e ele pode ser usado para remover o último item da lista ou um item em uma posição específica. Se você usar pop() sem argumentos, ele removerá e retornará o último item da lista. Se você fornecer um índice como argumento, ele removerá e retornará o item na posição especificada, mas ele não remove permanentemente, apenas remove da lista, ou seja, ele pode ser adicionado novamente.
# 25: A diferença entre dados['chave'] e dados.get(chave) é que dados[chave] irá gerar um erro se a chave não existir no dicionário, enquanto dados.get(chave) retornará None (ou um valor padrão especificado) se a chave não existir, evitando assim um erro.
# 26: Ao acessar uma chave inexistente com colchetes (dados['chave']), o Python gera um KeyError, indicando que a chave não foi encontrada no dicionário. Por outro lado, ao usar o método get (dados.get('chave')), o Python retorna None (ou um valor padrão especificado) se a chave não existir, sem gerar um erro. Portanto, usar get é uma maneira mais segura de acessar chaves em um dicionário quando não se tem certeza se a chave existe ou não.
# 27: O indice negativo em uma lista é usado para acessar os elementos a partir do final da lista. O índice -1 se refere ao último elemento, -2 ao penúltimo, e assim por diante. Por exemplo, se você tem uma lista chamada "lista" com os elementos [10, 20, 30], lista[-1] retornará 30, lista[-2] retornará 20, e lista[-3] retornará 10. O uso de índices negativos é útil para acessar elementos sem precisar conhecer o comprimento exato da lista.
# 28: A diferença entre for elemento in lista e for i in range(len(lista)) é que o primeiro itera diretamente sobre os elementos da lista, enquanto o segundo itera sobre os índices da lista. No primeiro caso, "elemento" representa cada item da lista em cada iteração, enquanto no segundo caso, "i" representa o índice de cada item, e você precisaria acessar o elemento usando lista[i] para obter o valor correspondente. O primeiro método é geralmente mais simples e mais legível quando você só precisa dos valores, enquanto o segundo pode ser útil quando você precisa dos índices para realizar operações adicionais.
# 29: Uma matriz em python é uma estrutura de dados bidimensional que pode ser representada como uma lista de listas ou usando bibliotecas como NumPy. Ela é usada para armazenar e manipular dados em formato tabular, onde cada elemento é acessado por meio de dois índices: um para a linha e outro para a coluna. Por exemplo, em uma matriz representada como m = [[1, 2], [3, 4]], m[0][0] acessa o elemento na primeira linha e primeira coluna (1), enquanto m[1][1] acessa o elemento na segunda linha e segunda coluna (4). 
# 30: O Numpy é uma biblioteca em Python que fornece suporte para arrays multidimensionais e matrizes, além de uma coleção de funções matemáticas para operar com esses arrays. Ele é amplamente utilizado para cálculos científicos e análise de dados devido à sua eficiência e facilidade de uso. O NumPy permite realizar operações como álgebra linear, transformações de Fourier, manipulação de dados e muito mais, tornando-o uma ferramenta essencial para cientistas de dados, engenheiros e pesquisadores que trabalham com grandes conjuntos de dados ou cálculos complexos.
